name: niai
description: Lookup similar Kanjis, Homonyms, Synonyms!

version: 1.0.0+3
versionName: 1.0

environment:
  sdk: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  http: ^0.12.0+2
  rxdart: ^0.22.0
  sticky_headers: ^0.1.7
  dynamic_theme: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
